name: Python CI

on:
  push:
    branches:
      - main  # Esto indica que el flujo de trabajo se ejecutar치 al hacer un push a la rama principal

jobs:
  test:
    runs-on: ubuntu-latest  # El flujo se ejecutar치 en un entorno de Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Primero se descarga el c칩digo desde el repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Se configura la versi칩n de Python que vamos a usar

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalamos las dependencias del proyecto

      - name: Run tests
        run: |
          pytest tests  # Ejecutamos las pruebas con pytest
